### ISSUE TITLE
PA3015: Property Removed: AnalysisOptions.DataflowAnalysisFlagStateToggledByUser

### ISSUE THREAD

**Issue by johannesschinzelcoleida** [microsoft/PowerApps-Tooling#493] opened 2023-09-12 10:48 UTC
**Describe the bug**

We are using the unpack solution action with the ProcessCanvasApp parameter set to true in our DevOps pipelines (v2). In one project, we have encountered an error when trying to run the pipeline after we have changed some buttons and toggles in the canvas app.
If we set ProcessCanvasApp to false, the solution can be unpacked without an error.

**To Reproduce**

1. Set ProcessCanvasApp to true in the step to unpack the solution
2. Run the DevOps pipeline

This is the error thrown by our pipeline (redacted for privacy):
```
-- unpacking Canvas app ***_***_9b485...
Unpack from D:\a\1\s\Power Platform solutions\PRJ1047***\PRJ1047***_unmanaged\CanvasApps\***_***_9b485_DocumentUri.msapp --> D:\a\1\s\Power Platform solutions\PRJ1047***\PRJ1047***_unmanaged\CanvasApps\src\***_***_9b485
  source format version: 0.24
Warning PA2001: Checksum mismatch. Checksum indicates that sources have been edited since they were unpacked. If this was intentional, ignore this warning.
Microsoft PowerPlatform CLI
Version: 1.26.5+g670cdf9
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions

Error: Error   PA3015: Property Removed: AnalysisOptions.DataflowAnalysisEnabled
Error   PA3015: Property Removed: AnalysisOptions.DataflowAnalysisFlagStateToggledByUser
Error   PA3011: Roundtrip validation on unpack failed. 
You have found a bug; this is not a specific bug, rather an indicator that some bug has been encountered.
Please open an issue and log the entirety of this error log at https://github.com/microsoft/PowerApps-Language-Tooling
```

**Comment by h-marti** [comment] 2023-09-12 12:43
We have exactly the same problem in our devops pipelines but only on certain PowerApps solutions.
We are currently trying to upgrade ALM Accelerator to the latest version to see if it fix the issue

**Comment by h-marti** [comment] 2023-09-12 14:59
We successfully updated ALM Accelerator with no evolution of our pipeline problem.

We tried to restore an old version of the application that was putting our pipeline to error and it just worked...

We are currently looking for what in the powerapp could bug the powershell pac command (yes we executed it locally as well)

**Comment by johannesschinzelcoleida** [comment] 2023-09-12 15:11
Yes, we experienced the same thing. It seems to be some change in the app that prevents the command from executing correctly, although the error message seems to point to something Dataflow-related.

**Comment by johannesschinzelcoleida** [comment] 2023-09-12 15:33
We are only seeing this problem with one app so far. Other (canvas) apps we have changed later still run through the unpack step without any issues.

**Comment by mitchellromanuik** [comment] 2023-09-12 18:04
I can confirm we are also experiencing this issue as well.

Appears PowerApps has gone through an updated. Upgraded PAC to v1.26.6 and problem still occurs.

Older apps still work until application is saved/published.

**Comment by fowl2** [comment] 2023-09-13 06:24
Also experiencing this issue. Error misleadingly looks like below in AzDO, until you dig further:

```
##[error]error: 1
##[error]failed: 
Unpacking Solution...
Read-only files will be over-written or deleted.
```

**Comment by CoreySutton** [comment] 2023-09-15 04:54
Also experiencing this issue across multiple versions of the power apps cli.

I have temporarily resolved the error by removing any usage of `--processCanvasApps` ([docs](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/solution#--processcanvasapps--pca-2)) when running `pac solution sync...`.

This prevents canvas apps from being unpacked but allows the unpacking of the other solution components.

**Comment by parkjdev** [comment] 2023-09-15 06:39
We are using the ALM Accelerator the pipeline does the same command. We successfully completed the pipeline on Mon 11th. Tried importing the same solution since Wednesday and getting this same error.

**Comment by CharlieCant** [comment] 2023-09-18 01:29
Confirming we are also experiencing the issue. 

Any canvas application that has had a change and is then saved and published in a solution that is the target of the unpack solution action with ProcessCanvasApp = true will throw the error.

Also confirming that setting the ProcessCanvasApp = false or running a pipeline against a solution where no update has been made to the canvas app won't throw the error.

**Comment by gytisa** [comment] 2023-09-18 15:47
The workaround is to downgrade App version to 3.23084.14.  https://github.com/microsoft/powerplatform-build-tools/issues/536

**Comment by clairewu0218** [comment] 2023-09-18 19:24
Thanks for the discussion. We are looking into it.

**Comment by sdhsynsci** [comment] 2023-09-20 14:50
> Thanks for the discussion. We are looking into it.

Any updates or workarounds? This has stopped our entire development process and postponed a go-live for clients?

**Comment by rfarris2000** [comment] 2023-09-20 15:33
> > Thanks for the discussion. We are looking into it.
> 
> Any updates or workarounds? This has stopped our entire development process and postponed a go-live for clients?

Downgrade the app authoring version to 3.23084.14 and then recommit.  This solved the issue for me.

**Comment by mitchellromanuik** [comment] 2023-09-20 17:04
> > > Thanks for the discussion. We are looking into it.
> > 
> > 
> > Any updates or workarounds? This has stopped our entire development process and postponed a go-live for clients?
> 
> Downgrade the app authoring version to 3.23084.14 and then recommit. This solved the issue for me.

https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/studio-versions

Will confirm suggested workaround provided by rfarris2000.

Provided link above for working instructions

**Comment by Cliveo** [comment] 2023-09-25 01:17
Is there any timeline for a permanent resolution? Rather not have our canvas apps pegged to an old version.

**Comment by akshar2401** [comment] 2023-09-25 13:59
Hey all, sorry for the inconvenience here. This was a regression caused by some changes in studio which was ultimately fixed in August. A new version 1.27.x of Pac cli came out last week and it has the fix for this issue. I'd recommend to update your pac cli version to the latest and it should fix this for you.

**Comment by vieira22** [comment] 2023-10-20 02:50
Hi Everyone, I have tried to update to latest CLI and same issue. Anything progress from anyone? Thanks!!!

**Comment by NavneetThekkumpat** [comment] 2023-10-25 14:22
@vieira22 Please let us know what version you are on. We could take a look at it. Also it would be great if you can send your .msapp to our team (paadvmakers AT microsoft DOT com)

**Comment by improving-jeffd** [comment] 2024-02-23 18:22
Seeing a similar error and can no longer try reverting to 3.23084.14. My errors are:
Error: Error   PA3015: Property Removed: TopParent.Children[0].Children[0].Rules[2].Category
Error   PA3015: Property Removed: TopParent.Children[0].Children[0].Rules[2].InvariantScript
Error   PA3015: Property Removed: TopParent.Children[0].Children[0].Rules[2].Property
Error   PA3015: Property Removed: TopParent.Children[0].Children[0].Rules[2].RuleProviderType

That repeats with increments in the references for the Children/Rules arrays.

**Closed** 2024-05-28 15:28 UTC
Labels: bug

**Comment by joudot** [comment] 2024-05-29 10:16
Interesting announcements. Any idea about the rollout dates for the native Git integration?

**Comment by petrochuk** [comment] 2024-05-29 12:49
> Interesting announcements. Any idea about the rollout dates for the native Git integration?

As it was said during Build conference native Git integration is in private preview right now.
